name: SentueLobby
main: com.sentue.dev.SentueLobby.Main
version: 1.0
description: >
             The Main Plugin For The Sentue Server
commands:
  test:
    description: Tests things on the lobby plugin
  dual:
    description: Command for the custom dualing plugin

